#!/usr/bin/env bash
# Write a Bash script that uses ssh

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo service nginx start
