#!/usr/bin/env bash
# Write a Bash script that uses ssh

apt-get -y update
apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
