#!/usr/bin/env bash
# Write a Bash script that uses ssh

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

sudo chmod -R 755 /var/www

echo 'Hello World!' |sudo tee  /var/www/html/index.html

echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i "/listen 80 default_server;/a error_page 404 /404.html;" /etc/nginx/sites-available/default
sed -i '14a \\tadd_header X-Served-By '"${HOSTNAME}"';' /etc/nginx/nginx.conf
sudo service nginx restart
