#!/usr/bin/env bash
# Write a Bash script that uses ssh

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend localnodes
        bind *:80
        mode http
        default_backend nodes
backend nodes
        balance roundrobin
        server 531033-web-01 52.6.173.34:80 check
        server 531033-web-02 52.3.248.217:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
