#!/usr/bin/env bash
# A script that displays Best School 10 times using a for loop.
# shellcheck disable=SC2009

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/holbertonscript.pid; exit" SIGQUIT

while true
do
	echo 'To infinity and beyond'
	sleep 2
done
