#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:

for num in {1..100}
do
	if (( num % 3 == 0 && num % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( num % 3 == 0 ))
	then
		echo "Fizz"
	elif (( num % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
