#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:

file="/etc/passwd"
l1=""
l2=""
l3=""

while IFS= read -r line
do
    l1="$(echo "$line" | cut -d":" -f1)"
    l2="$(echo "$line" | cut -d":" -f4)"
    l3="$(echo "$line" | cut -d":" -f6)"
    l4="$(echo "$line" | cut -d":" -f7)"
    l5="$(echo "$line" | cut -d":" -f3)"
    l6="$(echo "$line" | cut -d":" -f2)"
    l7="$(echo "$line" | cut -d":" -f5)"
    echo "The user ${l1} is part of the ${l2} gang, lives in ${l3} and rides ${l4}. ${l5}'s place is protected by the passcode ${l6}, more info about the user here: ${l7}"
done < "$file"
